# Generated by Django 5.2.7 on 2025-10-30 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('HARSH_BRAKING', 'Harsh Braking'), ('SPEEDING', 'Speeding'), ('AGGRESSIVE_DRIVING', 'Aggressive Driving'), ('DROWSINESS', 'Driver Drowsiness'), ('DISTRACTION', 'Driver Distraction'), ('PHONE_USAGE', 'Phone Usage While Driving'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of the incident', null=True)),
                ('location', models.JSONField(help_text='Incident location coordinates {lat, lng, address}')),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When the incident was detected')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the incident was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='vehicles.driver')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='vehicles.vehicle')),
                ('video_clips', models.ManyToManyField(blank=True, help_text='Associated video evidence', related_name='incidents', to='video.videoarchive')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Alert type/category', max_length=50)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('message', models.TextField(help_text='Alert message content')),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether alert has been acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.vehicle')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='incidents.incident')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
