# Generated by Django 5.2.7 on 2025-10-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to video file (S3 or local)', max_length=500)),
                ('duration', models.IntegerField(default=0, help_text='Video duration in seconds')),
                ('size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization and search')),
                ('thumbnail', models.CharField(blank=True, help_text='Path to thumbnail image', max_length=500, null=True)),
                ('camera_position', models.CharField(choices=[('FRONT', 'Front Camera'), ('CABIN', 'Cabin Camera'), ('REAR', 'Rear Camera')], default='FRONT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField(blank=True, help_text='Date when video will be automatically deleted', null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_archives', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'video_archives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_position', models.CharField(choices=[('FRONT', 'Front Camera'), ('CABIN', 'Cabin Camera'), ('REAR', 'Rear Camera')], default='FRONT', max_length=20)),
                ('stream_url', models.URLField(help_text='URL for live stream', max_length=500)),
                ('recording_url', models.URLField(blank=True, help_text='URL for recorded video', max_length=500, null=True)),
                ('status', models.CharField(choices=[('STARTING', 'Starting'), ('ACTIVE', 'Active'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='STARTING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_streams', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'video_streams',
                'ordering': ['-started_at'],
            },
        ),
    ]
