# Generated by Django 5.2.7 on 2025-10-30 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(help_text='Driver license number', max_length=50, unique=True)),
                ('license_expiry', models.DateField(help_text='License expiration date')),
                ('status', models.CharField(choices=[('ON_DUTY', 'On Duty'), ('OFF_DUTY', 'Off Duty'), ('ON_BREAK', 'On Break'), ('SUSPENDED', 'Suspended')], default='OFF_DUTY', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average driver rating (0-5)', max_digits=3)),
                ('total_trips', models.IntegerField(default=0, help_text='Total number of completed trips')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='Vehicle license plate number', max_length=20, unique=True)),
                ('make', models.CharField(help_text='Vehicle manufacturer', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model', max_length=50)),
                ('year', models.IntegerField(help_text='Manufacturing year')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True)),
                ('capacity', models.IntegerField(default=4, help_text='Passenger capacity')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='ACTIVE', max_length=20)),
                ('registration_date', models.DateField(blank=True, help_text='Vehicle registration date', null=True)),
                ('insurance_expiry', models.DateField(blank=True, help_text='Insurance expiration date', null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='vehicles.driver')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_location', models.JSONField(help_text='Start location coordinates {lat, lng, address}')),
                ('end_location', models.JSONField(blank=True, help_text='End location coordinates {lat, lng, address}', null=True)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, help_text='Trip distance in kilometers', max_digits=10)),
                ('duration', models.IntegerField(default=0, help_text='Trip duration in minutes')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('fare', models.DecimalField(decimal_places=2, default=0.0, help_text='Trip fare amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-start_time'],
            },
        ),
    ]
