# Generated by Django 5.2.7 on 2025-10-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPS_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate', max_digits=10)),
                ('speed', models.DecimalField(decimal_places=2, default=0.0, help_text='Speed in km/h', max_digits=6)),
                ('heading', models.DecimalField(decimal_places=2, default=0.0, help_text='Direction heading in degrees (0-360)', max_digits=5)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, help_text='Location accuracy in meters', max_digits=6)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude in meters', max_digits=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time when location was recorded')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'gps_locations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='gps_locatio_vehicle_f9a20c_idx'), models.Index(fields=['timestamp'], name='gps_locatio_timesta_50d5dd_idx')],
            },
        ),
    ]
