# Generated by Django 5.2.7 on 2025-10-30 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FLEET_PERFORMANCE', 'Fleet Performance'), ('DRIVER_PERFORMANCE', 'Driver Performance'), ('SAFETY_INCIDENT', 'Safety & Incident'), ('ROUTE_ANALYSIS', 'Route Analysis'), ('VEHICLE_MAINTENANCE', 'Vehicle Maintenance'), ('AI_INSIGHTS', 'AI Insights'), ('CUSTOM', 'Custom')], max_length=30)),
                ('title', models.CharField(help_text='Report title', max_length=200)),
                ('parameters', models.JSONField(help_text='Report parameters (date range, filters, etc.)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Path to generated report file', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Date when report will be automatically deleted', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if report generation failed', null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
